### ISSUE TITLE
index.html - build initial index page

### ISSUE THREAD

**Issue by fraziermork** [fraziermork/whereAreTheSirensGoing#1]

**Comment by fraziermork** [comment]
Use CDNs for jquery, handlebars (page.js)

**Comment by dzknj** [comment]
Got basic layout done. Created seperate sections for index results and overview, gave them class names and id's to make it easier for css and js. Added page names to header with classnames same as the section it belongs so it will hide when not wanted. Added handlebars template for results page for incidents. Added routes and dependencies, project routes order will probably have to be tweaked with once the JS gets done on them.
